stages:
  - test

secret_scan:
  image: zricethezav/gitleaks:latest
  stage: test
  script:
    - gitleaks detect --source . --verbose

dependency_audit:
  image: python:3.11
  stage: test
  script:
    - pip install pip-audit
    - pip-audit

tests:
  image: python:3.11
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install pytest pytest-cov
    - pytest --cov=.
